### ISSUE TITLE
plugin no influence at all at: www1.cbn.com/radio/superbook

### ISSUE THREAD

**Issue by chihwahli** [puddingspudding/persistent-video-volume#11]
Above website's music volume is not influenced by your plugin at all Both master volume and website specific setting don't work.

**Comment by puddingspudding** [comment]
Hi @chihwahli ,
Thanks for your feedback.

I've just uploaded a new version (0.9.1) for Firefox and Chrome which solves your problem with cbn.com.

**Comment by chihwahli** [comment]
Hello sir, madam,

Awesome. thank you for version 0.9.1. Both Firefox and Chrome are working as I change the volume inside your Extention or add on. Settings are also remembered now. What a super fast response.
