### ISSUE TITLE
music.youtube.com

### ISSUE THREAD

**Issue by chihwahli** [puddingspudding/persistent-video-volume#13]
Frequenty bug: every few minutes
Bug:enabled website to any x %, for example 50%, then after about a few minutes it resets to 100%. 

Repeatable: yes, very, very consistent

Link website where bug happens: music.youtube.com
Also: 

Cross reference with other websites: i notice a sudden increase in volume then going back to pre-set volume, this happens with some other websites that are not  music.youtube.com.
The difference with music.youtube.com is, that those other websites go back to the pre-set volume % again, but with music.youtube.com it will not go back, it will just jump to 100% 

Seems there are 2 bugs here....

**Comment by puddingspudding** [comment]
Hi @chihwahli 
Thanks for your feedback.
It looks like music.youtube.com resets the volume to the previously set value, using youtube's volume slider when the song reaches the end. I can always reproduce this behaviour by jumping to the end
This seems a bit random from youtube.

If you are using youtube's volume slider everything should work fine and the volume does not jump up or down
