### ISSUE TITLE
Cannot track new windows.

### ISSUE THREAD

**Issue by GOKUSSL4** [puddingspudding/persistent-video-volume#3]
I open a new window and it cannot interact with any website in that window. It is only able to interact with the first window. It opens and only recognizes my current selected tab on the first window.

**Comment by puddingspudding** [comment]
Hi @GOKUSSL4,
Thank you for creating this issue. I'll try to fix this in the next few days

**Comment by puddingspudding** [comment]
2ff1997b5787eecccedd9f478f055defc9a3c3e4

**Comment by puddingspudding** [comment]
Uploaded new version and will be available soon
