### ISSUE TITLE
[Suggestion] Per Site Config

### ISSUE THREAD

**Issue by drakray** [puddingspudding/persistent-video-volume#4]
Being disabled by default, and if enabled for a particular site, keep the volume level only for that site. Ex: 100% always(disabled), Facebook 75%, Youtube 80%, Tumblr 50%. etc. without having to change it everytime. That would be very nice, especially for site where audio playback have no volume control, like Tumblr and gaming webpage where you can only turn it on/off.

**Comment by GOKUSSL4** [comment]
Not enabled for website by default is a great idea as it conflicts with audio volume control elements of websites. It's really great for websites with no volume controls or elements in a website that are loud.

**Comment by puddingspudding** [comment]
Sorry for the late reply.

May discussed in #6
